GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Blog test",
  "author": "Author test",
  "URL": "blogtest.com",
  "likes": 10050
}
