GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Blog test",
  "author": "Author test",
  "URL": "blogtest.com",
  "likes": 10050
}


// RENDER TESTS

###
GET https://part3-2.onrender.com/api/blogs

###
POST https://part3-2.onrender.com/
Content-Type: application/json

{
  "name": "Rest API test for Render 3",
  "number": "672"
}
